name: resource history action
author: matsudamper
description: Record Linux Machine Resource History
# inputs
# outputs
runs:
  using: "node16"
  main: dist/main/index.js
  pre: dist/pre/index.js
  post: dist/post/index.js
