name: resource history action
author: matsudamper
description: Record Linux Machine Resource History
# inputs
# outputs
env: 
  MEMORY_FILE: /var/tmp/action-history-memory.txt
  CPU_FILE: /var/tmp/action-history-cpu.txt
runs:
  using: "node16"
  main: ./scripts/main.sh
  entrypoint: ./scripts/entrypoint.sh
  post-entrypoint: ./scripts/post-entrypoint.sh
