name: resource history action
author: matsudamper
description: Record Linux Machine Resource History
# inputs
# outputs
runs:
  env: 
    MEMORY_FILE: /var/tmp/action-history-memory.txt
    CPU_FILE: /var/tmp/action-history-cpu.txt
  using: "node16"
  main: main.js
  pre: pre.js
  post: post.js
